# Football Matches Statistics

## 1. Initial Exploration and Data Cleaning

The purpose of this notebook is to explore and clean the football dataset before performing the Exploratory Data Analysis (EDA).

This notebook follows the standard workflow:

In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

## 1.1 Load the dataset

In [48]:
df = pd.read_csv("dataset/football_matches_dataset.csv")

## 1.2. Initial Data Exploration

In [49]:
df.head()

,Unnamed: 0,home_team,away_team,date,league,season,home_score,away_score,home_xg,away_xg,...,home_defense_rating_last_2_home_matches,away_defense_rating_last_2_away_matches,home_midfield_rating_last_4_matches,away_midfield_rating_last_4_matches,home_midfield_rating_last_2_home_matches,away_midfield_rating_last_2_away_matches,home_attack_rating_last_4_matches,away_attack_rating_last_4_matches,home_attack_rating_last_2_home_matches,away_attack_rating_last_2_away_matches
0,0,Reims,Paris Saint Germain,August 08 2014,Ligue 1,2014/2015,2,2,1.37,2.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Evian Thonon Gaillard,Caen,August 09 2014,Ligue 1,2014/2015,0,3,0.81,1.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Guingamp,Saint-Etienne,August 09 2014,Ligue 1,2014/2015,0,2,0.63,1.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Lille,Metz,August 09 2014,Ligue 1,2014/2015,0,0,1.54,0.06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Montpellier,Bordeaux,August 09 2014,Ligue 1,2014/2015,0,1,1.02,0.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
df.shape

(16332, 55)

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16332 entries, 0 to 16331
Data columns (total 55 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Unnamed: 0                                16332 non-null  int64
 1   home_team                                 16332 non-null  object
 2   away_team                                 16332 non-null  object
 3   date                                      16332 non-null  object
 4   league                                    16332 non-null  object
 5   season                                    16332 non-null  object
 6   home_score                                16332 non-null  int64
 7   away_score                                16332 non-null  int64
 8   home_xg                                   16332 non-null  float64
 9   away_xg                                   16332 non-null  float64
 10  datetime                                  16332 non-null  object
 11  home_standings                            16332 non-null  int64
 12  away_standings                            16332 non-null  int64
 13  home_points                               16332 non-null  int64
 14  away_points                               16332 non-null  int64
 15  home_points_last_4_matches                16020 non-null  float64
 16  away_points_last_4_matches                16016 non-null  float64
 17  home_points_last_2_home_matches           16018 non-null  float64
 18  away_points_last_2_away_matches           16018 non-null  float64
 19  home_goals_last_4_matches                 16020 non-null  float64
 20  away_goals_last_4_matches                 16016 non-null  float64
 21  home_goals_last_2_home_matches            16018 non-null  float64
 22  away_goals_last_2_away_matches            16018 non-null  float64
 23  home_goals_against_last_4_matches         16020 non-null  float64
 24  away_goals_against_last_4_matches         16016 non-null  float64
 25  home_goals_against_last_2_home_matches    16018 non-null  float64
 26  away_goals_against_last_2_away_matches    16018 non-null  float64
 27  home_mean_xg_last_4_matches               16020 non-null  float64
 28  away_mean_xg_last_4_matches               16016 non-null  float64
 29  home_mean_xg_last_2_home_matches          16018 non-null  float64
 30  away_mean_xg_last_2_away_matches          16018 non-null  float64
 31  home_mean_xg_against_last_4_matches       16020 non-null  float64
 32  away_mean_xg_against_last_4_matches       16016 non-null  float64
 33  home_mean_xg_against_last_2_home_matches  16018 non-null  float64
 34  away_mean_xg_against_last_2_away_matches  16018 non-null  float64
 35  home_formation                            16332 non-null  int64
 36  away_formation                            16332 non-null  int64
 37  home_defense_rating                       16332 non-null  float64
 38  away_defense_rating                       16332 non-null  float64
 39  home_midfield_rating                      16332 non-null  float64
 40  away_midfield_rating                      16332 non-null  float64
 41  home_attack_rating                        16332 non-null  float64
 42  away_attack_rating                        16332 non-null  float64
 43  home_defense_rating_last_4_matches        16020 non-null  float64
 44  away_defense_rating_last_4_matches        16016 non-null  float64
 45  home_defense_rating_last_2_home_matches   16018 non-null  float64
 46  away_defense_rating_last_2_away_matches   16018 non-null  float64
 47  home_midfield_rating_last_4_matches       16020 non-null  float64
 48  away_midfield_rating_last_4_matches       16016 non-null  float64
 49  home_midfield_rating_last_2_home_matches  16018 non-null  float64
 50  away_midfield_rating_last_2_away_matches  16018 non-null  float64
 51  home_attack_rating_last_4_matches         16020 non-null  float64
 52  away_attack_rating_last_4_matches         16016 non-null  float64
 53  home_attack_rating_last_2_home_matches    16018 non-null  float64
 54  away_attack_rating_last_2_away_matches    16018 non-null  float64
dtypes: float64(40), int64(9), object(6)
memory usage: 6.9+ MB

In [52]:
list(df.columns)

['Unnamed: 0',
 'home_team',
 'away_team',
 'date',
 'league',
 'season',
 'home_score',
 'away_score',
 'home_xg',
 'away_xg',
 'datetime',
 'home_standings',
 'away_standings',
 'home_points',
 'away_points',
 'home_points_last_4_matches',
 'away_points_last_4_matches',
 'home_points_last_2_home_matches',
 'away_points_last_2_away_matches',
 'home_goals_last_4_matches',
 'away_goals_last_4_matches',
 'home_goals_last_2_home_matches',
 'away_goals_last_2_away_matches',
 'home_goals_against_last_4_matches',
 'away_goals_against_last_4_matches',
 'home_goals_against_last_2_home_matches',
 'away_goals_against_last_2_away_matches',
 'home_mean_xg_last_4_matches',
 'away_mean_xg_last_4_matches',
 'home_mean_xg_last_2_home_matches',
 'away_mean_xg_last_2_away_matches',
 'home_mean_xg_against_last_4_matches',
 'away_mean_xg_against_last_4_matches',
 'home_mean_xg_against_last_2_home_matches',
 'away_mean_xg_against_last_2_away_matches',
 'home_formation',
 'away_formation',
 'home_defense_rating',
 'away_defense_rating',
 'home_midfield_rating',
 'away_midfield_rating',
 'home_attack_rating',
 'away_attack_rating',
 'home_defense_rating_last_4_matches',
 'away_defense_rating_last_4_matches',
 'home_defense_rating_last_2_home_matches',
 'away_defense_rating_last_2_away_matches',
 'home_midfield_rating_last_4_matches',
 'away_midfield_rating_last_4_matches',
 'home_midfield_rating_last_2_home_matches',
 'away_midfield_rating_last_2_away_matches',
 'home_attack_rating_last_4_matches',
 'away_attack_rating_last_4_matches',
 'home_attack_rating_last_2_home_matches',
 'away_attack_rating_last_2_away_matches']

In [53]:
[col for col in df.columns if "id" in col.lower()]

['home_midfield_rating',
 'away_midfield_rating',
 'home_midfield_rating_last_4_matches',
 'away_midfield_rating_last_4_matches',
 'home_midfield_rating_last_2_home_matches',
 'away_midfield_rating_last_2_away_matches']

In [54]:
df["Unnamed: 0"].head()

0    0
1    1
2    2
3    3
4    4
Name: Unnamed: 0, dtype: int64

In [55]:
df["Unnamed: 0"].duplicated().sum()

np.int64(0)

In [56]:
df.describe()

,Unnamed: 0,home_score,away_score,home_xg,away_xg,home_standings,away_standings,home_points,away_points,home_points_last_4_matches,...,home_defense_rating_last_2_home_matches,away_defense_rating_last_2_away_matches,home_midfield_rating_last_4_matches,away_midfield_rating_last_4_matches,home_midfield_rating_last_2_home_matches,away_midfield_rating_last_2_away_matches,home_attack_rating_last_4_matches,away_attack_rating_last_4_matches,home_attack_rating_last_2_home_matches,away_attack_rating_last_2_away_matches
count,16332.000000,16332.000000,16332.000000,16332.000000,16332.000000,16332.000000,16332.000000,16332.000000,16332.000000,16020.000000,...,16018.000000,16018.000000,16020.000000,16016.000000,16018.000000,16018.000000,16020.000000,16016.000000,16018.000000,16018.000000
mean,8165.500000,1.537595,1.213079,1.519489,1.198238,10.784778,10.647869,24.714487,24.902951,5.437765,...,6.850295,6.758092,6.876918,6.892891,6.967077,6.803555,6.936985,6.952650,7.040911,6.848876
std,4714.786634,1.310895,1.166409,0.898103,0.791728,5.592583,5.570980,17.915548,17.895257,2.938398,...,0.341491,0.352362,0.302985,0.304563,0.387721,0.372287,0.413593,0.415172,0.546994,0.506123
min,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,...,5.368333,5.333167,5.952500,5.925833,5.615000,5.570833,5.796250,5.857500,5.660000,5.545000
25%,4082.750000,1.000000,0.000000,0.850000,0.600000,6.000000,6.000000,10.000000,11.000000,3.000000,...,6.617000,6.524000,6.665625,6.681667,6.693333,6.542500,6.638750,6.660729,6.648333,6.480000
50%,8165.500000,1.000000,1.000000,1.360000,1.050000,11.000000,11.000000,22.000000,22.000000,5.000000,...,6.852750,6.754250,6.850000,6.866875,6.938125,6.776667,6.887500,6.901250,6.977500,6.777500
75%,12248.250000,2.000000,2.000000,2.030000,1.620000,16.000000,15.000000,36.000000,36.000000,7.000000,...,7.084833,7.000000,7.063333,7.078000,7.211667,7.027500,7.175417,7.189167,7.355625,7.146458
max,16331.000000,10.000000,9.000000,6.880000,6.500000,20.000000,20.000000,94.000000,97.000000,12.000000,...,8.156000,7.941000,8.335833,8.460000,8.675000,8.716250,9.293750,9.292500,9.650000,9.635000

In [57]:
df.describe(include="all")

,Unnamed: 0,home_team,away_team,date,league,season,home_score,away_score,home_xg,away_xg,...,home_defense_rating_last_2_home_matches,away_defense_rating_last_2_away_matches,home_midfield_rating_last_4_matches,away_midfield_rating_last_4_matches,home_midfield_rating_last_2_home_matches,away_midfield_rating_last_2_away_matches,home_attack_rating_last_4_matches,away_attack_rating_last_4_matches,home_attack_rating_last_2_home_matches,away_attack_rating_last_2_away_matches
count,16332.000000,16332,16332,16332,16332,16332,16332.000000,16332.000000,16332.000000,16332.000000,...,16018.000000,16018.000000,16020.000000,16016.000000,16018.000000,16018.000000,16020.000000,16016.000000,16018.000000,16018.000000
unique,NaN,157,157,1655,5,9,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Barcelona,Napoli,December 22 2018,EPL,2014/2015,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,171,171,37,3420,1826,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,8165.500000,NaN,NaN,NaN,NaN,NaN,1.537595,1.213079,1.519489,1.198238,...,6.850295,6.758092,6.876918,6.892891,6.967077,6.803555,6.936985,6.952650,7.040911,6.848876
std,4714.786634,NaN,NaN,NaN,NaN,NaN,1.310895,1.166409,0.898103,0.791728,...,0.341491,0.352362,0.302985,0.304563,0.387721,0.372287,0.413593,0.415172,0.546994,0.506123
min,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,5.368333,5.333167,5.952500,5.925833,5.615000,5.570833,5.796250,5.857500,5.660000,5.545000
25%,4082.750000,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.850000,0.600000,...,6.617000,6.524000,6.665625,6.681667,6.693333,6.542500,6.638750,6.660729,6.648333,6.480000
50%,8165.500000,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.360000,1.050000,...,6.852750,6.754250,6.850000,6.866875,6.938125,6.776667,6.887500,6.901250,6.977500,6.777500
75%,12248.250000,NaN,NaN,NaN,NaN,NaN,2.000000,2.000000,2.030000,1.620000,...,7.084833,7.000000,7.063333,7.078000,7.211667,7.027500,7.175417,7.189167,7.355625,7.146458
max,16331.000000,NaN,NaN,NaN,NaN,NaN,10.000000,9.000000,6.880000,6.500000,...,8.156000,7.941000,8.335833,8.460000,8.675000,8.716250,9.293750,9.292500,9.650000,9.635000

## 1.3. Missing Values

We checked for missing values to identify incomplete records and determine whether they should be removed, filled, or kept for further analysis.

In [58]:
df.isnull().sum()

Unnamed: 0                                    0
home_team                                     0
away_team                                     0
date                                          0
league                                        0
season                                        0
home_score                                    0
away_score                                    0
home_xg                                       0
away_xg                                       0
datetime                                      0
home_standings                                0
away_standings                                0
home_points                                   0
away_points                                   0
home_points_last_4_matches                  312
away_points_last_4_matches                  316
home_points_last_2_home_matches             314
away_points_last_2_away_matches             314
home_goals_last_4_matches                   312
away_goals_last_4_matches                   316
home_goals_last_2_home_matches              314
away_goals_last_2_away_matches              314
home_goals_against_last_4_matches           312
away_goals_against_last_4_matches           316
home_goals_against_last_2_home_matches      314
away_goals_against_last_2_away_matches      314
home_mean_xg_last_4_matches                 312
away_mean_xg_last_4_matches                 316
home_mean_xg_last_2_home_matches            314
away_mean_xg_last_2_away_matches            314
home_mean_xg_against_last_4_matches         312
away_mean_xg_against_last_4_matches         316
home_mean_xg_against_last_2_home_matches    314
away_mean_xg_against_last_2_away_matches    314
home_formation                                0
away_formation                                0
home_defense_rating                           0
away_defense_rating                           0
home_midfield_rating                          0
away_midfield_rating                          0
home_attack_rating                            0
away_attack_rating                            0
home_defense_rating_last_4_matches          312
away_defense_rating_last_4_matches          316
home_defense_rating_last_2_home_matches     314
away_defense_rating_last_2_away_matches     314
home_midfield_rating_last_4_matches         312
away_midfield_rating_last_4_matches         316
home_midfield_rating_last_2_home_matches    314
away_midfield_rating_last_2_away_matches    314
home_attack_rating_last_4_matches           312
away_attack_rating_last_4_matches           316
home_attack_rating_last_2_home_matches      314
away_attack_rating_last_2_away_matches      314
dtype: int64

In [59]:
df.isnull().sum().sort_values(ascending=False) #ordering in a DESC way

away_points_last_4_matches                  316
away_attack_rating_last_4_matches           316
away_goals_against_last_4_matches           316
away_midfield_rating_last_4_matches         316
away_goals_last_4_matches                   316
away_defense_rating_last_4_matches          316
away_mean_xg_last_4_matches                 316
away_mean_xg_against_last_4_matches         316
away_attack_rating_last_2_away_matches      314
away_goals_against_last_2_away_matches      314
home_goals_against_last_2_home_matches      314
away_mean_xg_last_2_away_matches            314
away_goals_last_2_away_matches              314
home_goals_last_2_home_matches              314
away_points_last_2_away_matches             314
home_points_last_2_home_matches             314
home_mean_xg_against_last_2_home_matches    314
away_mean_xg_against_last_2_away_matches    314
home_defense_rating_last_2_home_matches     314
away_defense_rating_last_2_away_matches     314
home_midfield_rating_last_2_home_matches    314
away_midfield_rating_last_2_away_matches    314
home_attack_rating_last_2_home_matches      314
home_mean_xg_last_2_home_matches            314
home_defense_rating_last_4_matches          312
home_mean_xg_against_last_4_matches         312
home_midfield_rating_last_4_matches         312
home_attack_rating_last_4_matches           312
home_mean_xg_last_4_matches                 312
home_goals_last_4_matches                   312
home_points_last_4_matches                  312
home_goals_against_last_4_matches           312
home_team                                     0
home_standings                                0
away_team                                     0
date                                          0
league                                        0
season                                        0
home_score                                    0
away_score                                    0
home_xg                                       0
away_xg                                       0
datetime                                      0
away_attack_rating                            0
away_standings                                0
home_attack_rating                            0
away_midfield_rating                          0
home_midfield_rating                          0
away_defense_rating                           0
home_defense_rating                           0
away_formation                                0
home_formation                                0
home_points                                   0
away_points                                   0
Unnamed: 0                                    0
dtype: int64

In [60]:
missing = df.isnull().sum()     #check

missing_percentage = (missing / len(df)) * 100

pd.DataFrame({
    "Missing Values": missing,
    "Percentage": missing_percentage.round(2)
}).sort_values("Missing Values", ascending=False)

                                          Missing Values  Percentage
away_points_last_4_matches                           316        1.93
away_attack_rating_last_4_matches                    316        1.93
away_goals_against_last_4_matches                    316        1.93
away_midfield_rating_last_4_matches                  316        1.93
away_goals_last_4_matches                            316        1.93
away_defense_rating_last_4_matches                   316        1.93
away_mean_xg_last_4_matches                          316        1.93
away_mean_xg_against_last_4_matches                  316        1.93
away_attack_rating_last_2_away_matches               314        1.92
away_goals_against_last_2_away_matches               314        1.92
home_goals_against_last_2_home_matches               314        1.92
away_mean_xg_last_2_away_matches                     314        1.92
away_goals_last_2_away_matches                       314        1.92
home_goals_last_2_home_matches                       314        1.92
away_points_last_2_away_matches                      314        1.92
home_points_last_2_home_matches                      314        1.92
home_mean_xg_against_last_2_home_matches             314        1.92
away_mean_xg_against_last_2_away_matches             314        1.92
home_defense_rating_last_2_home_matches              314        1.92
away_defense_rating_last_2_away_matches              314        1.92
home_midfield_rating_last_2_home_matches             314        1.92
away_midfield_rating_last_2_away_matches             314        1.92
home_attack_rating_last_2_home_matches               314        1.92
home_mean_xg_last_2_home_matches                     314        1.92
home_defense_rating_last_4_matches                   312        1.91
home_mean_xg_against_last_4_matches                  312        1.91
home_midfield_rating_last_4_matches                  312        1.91
home_attack_rating_last_4_matches                    312        1.91
home_mean_xg_last_4_matches                          312        1.91
home_goals_last_4_matches                            312        1.91
home_points_last_4_matches                           312        1.91
home_goals_against_last_4_matches                    312        1.91
home_team                                              0        0.00
home_standings                                         0        0.00
away_team                                              0        0.00
date                                                   0        0.00
league                                                 0        0.00
season                                                 0        0.00
home_score                                             0        0.00
away_score                                             0        0.00
home_xg                                                0        0.00
away_xg                                                0        0.00
datetime                                               0        0.00
away_attack_rating                                     0        0.00
away_standings                                         0        0.00
home_attack_rating                                     0        0.00
away_midfield_rating                                   0        0.00
home_midfield_rating                                   0        0.00
away_defense_rating                                    0        0.00
home_defense_rating                                    0        0.00
away_formation                                         0        0.00
home_formation                                         0        0.00
home_points                                            0        0.00
away_points                                            0        0.00
Unnamed: 0                                             0        0.00

Findings of isnull:

Several columns related to previous team performance contain missing values.

These missing values are expected because, at the beginning of each season, teams have not yet played enough matches to calculate previous statistics.

At this stage, no rows will be removed until we evaluate whether these missing values affect our research questions.

## 1.4. Duplicate Rows

We checked whether the dataset contains duplicated rows that could affect the analysis.

In [61]:
df.duplicated().sum()

np.int64(0)

Where not found any duplicated rows "0", so, no duplicate removal is required.

## 1.5. Index Column Review

The dataset contains an additional column called `Unnamed: 0`.

This column appears to be an automatically generated index from a previous CSV export rather than a meaningful identifier.

We verified that it contains unique values, but it will not be used in the analysis.

In [62]:
df["Unnamed: 0"].duplicated().sum()

np.int64(0)

This column will be removed during the data cleaning process because it does not provide analytical value.

## 1.6. Unique Values

We checked the number of unique values in each column to better understand which variables are categorical, numerical, or identifiers.

In [63]:
unique_values = pd.DataFrame({
    "Unique Values": df.nunique()
}).sort_values("Unique Values", ascending=False)

unique_values

                                          Unique Values
Unnamed: 0                                        16332
home_midfield_rating_last_4_matches                9917
away_midfield_rating_last_4_matches                9778
home_defense_rating_last_4_matches                 8701
away_defense_rating_last_4_matches                 8671
away_midfield_rating_last_2_away_matches           6856
home_midfield_rating_last_2_home_matches           6737
away_defense_rating_last_2_away_matches            6509
home_defense_rating_last_2_home_matches            6175
away_attack_rating_last_4_matches                  6061
home_attack_rating_last_4_matches                  6039
home_attack_rating_last_2_home_matches             4016
away_defense_rating                                3916
home_defense_rating                                3770
away_attack_rating_last_2_away_matches             3770
home_midfield_rating                               3464
away_midfield_rating                               3447
home_attack_rating                                 2138
away_attack_rating                                 1995
away_mean_xg_last_4_matches                        1837
home_mean_xg_last_4_matches                        1787
home_mean_xg_against_last_4_matches                1707
away_mean_xg_against_last_4_matches                1701
date                                               1655
datetime                                           1655
home_mean_xg_last_2_home_matches                   1005
away_mean_xg_against_last_2_away_matches            966
away_mean_xg_last_2_away_matches                    895
home_mean_xg_against_last_2_home_matches            868
home_xg                                             519
away_xg                                             454
away_team                                           157
home_team                                           157
away_points                                          97
home_points                                          94
away_goals_last_4_matches                            22
home_goals_last_4_matches                            22
home_goals_against_last_4_matches                    20
away_goals_against_last_4_matches                    20
away_standings                                       20
home_standings                                       20
home_goals_last_2_home_matches                       15
away_goals_last_2_away_matches                       14
away_goals_against_last_2_away_matches               14
home_goals_against_last_2_home_matches               13
home_points_last_4_matches                           12
away_points_last_4_matches                           12
home_score                                           11
away_score                                           10
season                                                9
away_points_last_2_away_matches                       6
home_points_last_2_home_matches                       6
away_formation                                        5
league                                                5
home_formation                                        5

Findings of Unique Values

The unique values check helps identify categorical variables such as `league`, `season`, and team formations, as well as high-cardinality variables such as `home_team`, `away_team`, and `datetime`.

The `Unnamed: 0` column appears to be an automatically generated index from a previous CSV export and does not provide analytical value. Therefore, it will be removed during the data cleaning process.

## 1.7. Data Types

We reviewed the data types of each column to identify variables that may require conversion.

In [64]:
df.dtypes

Unnamed: 0                                    int64
home_team                                    object
away_team                                    object
date                                         object
league                                       object
season                                       object
home_score                                    int64
away_score                                    int64
home_xg                                     float64
away_xg                                     float64
datetime                                     object
home_standings                                int64
away_standings                                int64
home_points                                   int64
away_points                                   int64
home_points_last_4_matches                  float64
away_points_last_4_matches                  float64
home_points_last_2_home_matches             float64
away_points_last_2_away_matches             float64
home_goals_last_4_matches                   float64
away_goals_last_4_matches                   float64
home_goals_last_2_home_matches              float64
away_goals_last_2_away_matches              float64
home_goals_against_last_4_matches           float64
away_goals_against_last_4_matches           float64
home_goals_against_last_2_home_matches      float64
away_goals_against_last_2_away_matches      float64
home_mean_xg_last_4_matches                 float64
away_mean_xg_last_4_matches                 float64
home_mean_xg_last_2_home_matches            float64
away_mean_xg_last_2_away_matches            float64
home_mean_xg_against_last_4_matches         float64
away_mean_xg_against_last_4_matches         float64
home_mean_xg_against_last_2_home_matches    float64
away_mean_xg_against_last_2_away_matches    float64
home_formation                                int64
away_formation                                int64
home_defense_rating                         float64
away_defense_rating                         float64
home_midfield_rating                        float64
away_midfield_rating                        float64
home_attack_rating                          float64
away_attack_rating                          float64
home_defense_rating_last_4_matches          float64
away_defense_rating_last_4_matches          float64
home_defense_rating_last_2_home_matches     float64
away_defense_rating_last_2_away_matches     float64
home_midfield_rating_last_4_matches         float64
away_midfield_rating_last_4_matches         float64
home_midfield_rating_last_2_home_matches    float64
away_midfield_rating_last_2_away_matches    float64
home_attack_rating_last_4_matches           float64
away_attack_rating_last_4_matches           float64
home_attack_rating_last_2_home_matches      float64
away_attack_rating_last_2_away_matches      float64
dtype: object

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16332 entries, 0 to 16331
Data columns (total 55 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Unnamed: 0                                16332 non-null  int64
 1   home_team                                 16332 non-null  object
 2   away_team                                 16332 non-null  object
 3   date                                      16332 non-null  object
 4   league                                    16332 non-null  object
 5   season                                    16332 non-null  object
 6   home_score                                16332 non-null  int64
 7   away_score                                16332 non-null  int64
 8   home_xg                                   16332 non-null  float64
 9   away_xg                                   16332 non-null  float64
 10  datetime                                  16332 non-null  object
 11  home_standings                            16332 non-null  int64
 12  away_standings                            16332 non-null  int64
 13  home_points                               16332 non-null  int64
 14  away_points                               16332 non-null  int64
 15  home_points_last_4_matches                16020 non-null  float64
 16  away_points_last_4_matches                16016 non-null  float64
 17  home_points_last_2_home_matches           16018 non-null  float64
 18  away_points_last_2_away_matches           16018 non-null  float64
 19  home_goals_last_4_matches                 16020 non-null  float64
 20  away_goals_last_4_matches                 16016 non-null  float64
 21  home_goals_last_2_home_matches            16018 non-null  float64
 22  away_goals_last_2_away_matches            16018 non-null  float64
 23  home_goals_against_last_4_matches         16020 non-null  float64
 24  away_goals_against_last_4_matches         16016 non-null  float64
 25  home_goals_against_last_2_home_matches    16018 non-null  float64
 26  away_goals_against_last_2_away_matches    16018 non-null  float64
 27  home_mean_xg_last_4_matches               16020 non-null  float64
 28  away_mean_xg_last_4_matches               16016 non-null  float64
 29  home_mean_xg_last_2_home_matches          16018 non-null  float64
 30  away_mean_xg_last_2_away_matches          16018 non-null  float64
 31  home_mean_xg_against_last_4_matches       16020 non-null  float64
 32  away_mean_xg_against_last_4_matches       16016 non-null  float64
 33  home_mean_xg_against_last_2_home_matches  16018 non-null  float64
 34  away_mean_xg_against_last_2_away_matches  16018 non-null  float64
 35  home_formation                            16332 non-null  int64
 36  away_formation                            16332 non-null  int64
 37  home_defense_rating                       16332 non-null  float64
 38  away_defense_rating                       16332 non-null  float64
 39  home_midfield_rating                      16332 non-null  float64
 40  away_midfield_rating                      16332 non-null  float64
 41  home_attack_rating                        16332 non-null  float64
 42  away_attack_rating                        16332 non-null  float64
 43  home_defense_rating_last_4_matches        16020 non-null  float64
 44  away_defense_rating_last_4_matches        16016 non-null  float64
 45  home_defense_rating_last_2_home_matches   16018 non-null  float64
 46  away_defense_rating_last_2_away_matches   16018 non-null  float64
 47  home_midfield_rating_last_4_matches       16020 non-null  float64
 48  away_midfield_rating_last_4_matches       16016 non-null  float64
 49  home_midfield_rating_last_2_home_matches  16018 non-null  float64
 50  away_midfield_rating_last_2_away_matches  16018 non-null  float64
 51  home_attack_rating_last_4_matches         16020 non-null  float64
 52  away_attack_rating_last_4_matches         16016 non-null  float64
 53  home_attack_rating_last_2_home_matches    16018 non-null  float64
 54  away_attack_rating_last_2_away_matches    16018 non-null  float64
dtypes: float64(40), int64(9), object(6)
memory usage: 6.9+ MB

Findings:

Most variables have the expected data types.

However, the `date` and `datetime` columns should be reviewed to determine which one will be used in the final dataset.

## 1.8. Check Invalid Values

In [66]:
(df["home_score"] < 0).sum()

np.int64(0)

In [67]:
(df["home_xg"] < 0).sum()

np.int64(0)

## 1.9. Check Categorical Values

Leagues

In [68]:
df["league"].value_counts()

league
EPL           3420
La liga       3420
Serie A       3420
Ligue 1       3318
Bundesliga    2754
Name: count, dtype: int64

Seasons

In [69]:
df["season"].value_counts()

season
2014/2015    1826
2015/2016    1826
2017/2018    1826
2018/2019    1826
2020/2021    1826
2021/2022    1826
2022/2023    1826
2016/2017    1825
2019/2020    1725
Name: count, dtype: int64

Formations

In [70]:
df["home_formation"].value_counts()

home_formation
0    8892
2    3561
3    2136
1    1740
4       3
Name: count, dtype: int64

## 1.10. Football-Specific Data Validation

Will check data which cannot be negative for the project

In [71]:
# Goals cannot be negative
(df["home_score"] < 0).sum()
(df["away_score"] < 0).sum()

np.int64(0)

In [72]:
# Expected Goals cannot be negative
(df["home_xg"] < 0).sum()
(df["away_xg"] < 0).sum()

np.int64(0)

In [73]:
# Current points should not be negative
(df["home_points"] < 0).sum()
(df["away_points"] < 0).sum()

np.int64(0)

## Quick Summary

In [74]:
summary = pd.DataFrame({
    "Data Type": df.dtypes,
    "Missing Values": df.isnull().sum(),
    "Unique Values": df.nunique()
})

summary

,Data Type,Missing Values,Unique Values
Unnamed: 0,int64,0,16332
home_team,object,0,157
away_team,object,0,157
date,object,0,1655
league,object,0,5
season,object,0,9
home_score,int64,0,11
away_score,int64,0,10
home_xg,float64,0,519
away_xg,float64,0,454
datetime,object,0,1655
home_standings,int64,0,20
away_standings,int64,0,20
home_points,int64,0,94
away_points,int64,0,97
home_points_last_4_matches,float64,312,12
away_points_last_4_matches,float64,316,12
home_points_last_2_home_matches,float64,314,6
away_points_last_2_away_matches,float64,314,6
home_goals_last_4_matches,float64,312,22
away_goals_last_4_matches,float64,316,22
home_goals_last_2_home_matches,float64,314,15
away_goals_last_2_away_matches,float64,314,14
home_goals_against_last_4_matches,float64,312,20
away_goals_against_last_4_matches,float64,316,20
home_goals_against_last_2_home_matches,float64,314,13
away_goals_against_last_2_away_matches,float64,314,14
home_mean_xg_last_4_matches,float64,312,1787
away_mean_xg_last_4_matches,float64,316,1837
home_mean_xg_last_2_home_matches,float64,314,1005
away_mean_xg_last_2_away_matches,float64,314,895
home_mean_xg_against_last_4_matches,float64,312,1707
away_mean_xg_against_last_4_matches,float64,316,1701
home_mean_xg_against_last_2_home_matches,float64,314,868
away_mean_xg_against_last_2_away_matches,float64,314,966
home_formation,int64,0,5
away_formation,int64,0,5
home_defense_rating,float64,0,3770
away_defense_rating,float64,0,3916
home_midfield_rating,float64,0,3464
away_midfield_rating,float64,0,3447
home_attack_rating,float64,0,2138
away_attack_rating,float64,0,1995
home_defense_rating_last_4_matches,float64,312,8701
away_defense_rating_last_4_matches,float64,316,8671
home_defense_rating_last_2_home_matches,float64,314,6175
away_defense_rating_last_2_away_matches,float64,314,6509
home_midfield_rating_last_4_matches,float64,312,9917
away_midfield_rating_last_4_matches,float64,316,9778
home_midfield_rating_last_2_home_matches,float64,314,6737
away_midfield_rating_last_2_away_matches,float64,314,6856
home_attack_rating_last_4_matches,float64,312,6039
away_attack_rating_last_4_matches,float64,316,6061
home_attack_rating_last_2_home_matches,float64,314,4016
away_attack_rating_last_2_away_matches,float64,314,3770

# 2. Initial Data Cleaning

### Planned Cleaning Actions

Based on the initial exploration, the following cleaning decisions will be applied:

- Remove the `Unnamed: 0` column because it is an exported index.
- Convert the `datetime` column to datetime format.
- Evaluate whether the `date` column is redundant.
- Keep missing values in previous-performance variables until we determine whether they affect our research questions.
- Create new engineered features for the analysis. (AS EXTRA)

## 2.1. Removing the "Unnamed: 0" column

In [75]:
clean_df = df.drop(columns=["Unnamed: 0"])

In [76]:
df.head()

,Unnamed: 0,home_team,away_team,date,league,season,home_score,away_score,home_xg,away_xg,...,home_defense_rating_last_2_home_matches,away_defense_rating_last_2_away_matches,home_midfield_rating_last_4_matches,away_midfield_rating_last_4_matches,home_midfield_rating_last_2_home_matches,away_midfield_rating_last_2_away_matches,home_attack_rating_last_4_matches,away_attack_rating_last_4_matches,home_attack_rating_last_2_home_matches,away_attack_rating_last_2_away_matches
0,0,Reims,Paris Saint Germain,August 08 2014,Ligue 1,2014/2015,2,2,1.37,2.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Evian Thonon Gaillard,Caen,August 09 2014,Ligue 1,2014/2015,0,3,0.81,1.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Guingamp,Saint-Etienne,August 09 2014,Ligue 1,2014/2015,0,2,0.63,1.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Lille,Metz,August 09 2014,Ligue 1,2014/2015,0,0,1.54,0.06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Montpellier,Bordeaux,August 09 2014,Ligue 1,2014/2015,0,1,1.02,0.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
clean_df.head()

,home_team,away_team,date,league,season,home_score,away_score,home_xg,away_xg,datetime,...,home_defense_rating_last_2_home_matches,away_defense_rating_last_2_away_matches,home_midfield_rating_last_4_matches,away_midfield_rating_last_4_matches,home_midfield_rating_last_2_home_matches,away_midfield_rating_last_2_away_matches,home_attack_rating_last_4_matches,away_attack_rating_last_4_matches,home_attack_rating_last_2_home_matches,away_attack_rating_last_2_away_matches
0,Reims,Paris Saint Germain,August 08 2014,Ligue 1,2014/2015,2,2,1.37,2.66,2014-08-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Evian Thonon Gaillard,Caen,August 09 2014,Ligue 1,2014/2015,0,3,0.81,1.24,2014-08-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Guingamp,Saint-Etienne,August 09 2014,Ligue 1,2014/2015,0,2,0.63,1.50,2014-08-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Lille,Metz,August 09 2014,Ligue 1,2014/2015,0,0,1.54,0.06,2014-08-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Montpellier,Bordeaux,August 09 2014,Ligue 1,2014/2015,0,1,1.02,0.75,2014-08-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Creating a new DataFrame as **"clean_df"** to storage all our changes from de origina "df"

We passed from **"df"** with 55 columns, to **"clean_df"**(new ) with 54 columns.

## 2.2. Check and compare **"date"** and **"datetime"** columns

In [78]:
clean_df[["date", "datetime"]].head()

             date    datetime
0  August 08 2014  2014-08-08
1  August 09 2014  2014-08-09
2  August 09 2014  2014-08-09
3  August 09 2014  2014-08-09
4  August 09 2014  2014-08-09

In [79]:
clean_df[["date", "datetime"]].dtypes

date        object
datetime    object
dtype: object

In [80]:
clean_df["datetime"] = pd.to_datetime(clean_df["datetime"])

With this step we change the type od `datetime` to a real datetime64[ns]

In [81]:
clean_df[["date", "datetime"]].dtypes

date                object
datetime    datetime64[ns]
dtype: object

In [82]:
same_date = (clean_df["date"] == clean_df["datetime"].dt.strftime("%B %d %Y")) #.dt panda serie for dates, 
same_date.all()

np.True_

Both columns have the same dates


### Cleaning Decision

The dataset contains two columns representing the match date.

- `date` stores the date as a text string.
- `datetime` stores the same information in a format that can be converted into a proper datetime object.

At this stage, both columns will be kept until **THE TEAM** agrees on which one should be used in the final cleaned dataset.

NOTE: i will go by `datetime`, for better uses in the future, where we could access to years (["datetime"].dt.year), months (.dt.month), day (.dt.day_name())...

# 3. Feature Engineering

In this section, we create new variables from the existing columns to support the analysis of our four research questions.

These new features will help us compare match results, goals, Expected Goals (xG), team form, points, ratings, and formations more clearly.

### 3.1. Match Result

To simplify the analysis, we created a new categorical variable called `match_result`.

Instead of comparing home and away goals repeatedly, this feature directly identifies whether the match ended in a Home Win, Draw, or Away Win.

This feature will be used throughout the EDA and SQL analysis, as it supports all four research questions.

In [83]:
clean_df.head(1) #exploring the table for getting the columns which will be needed

,home_team,away_team,date,league,season,home_score,away_score,home_xg,away_xg,datetime,...,home_defense_rating_last_2_home_matches,away_defense_rating_last_2_away_matches,home_midfield_rating_last_4_matches,away_midfield_rating_last_4_matches,home_midfield_rating_last_2_home_matches,away_midfield_rating_last_2_away_matches,home_attack_rating_last_4_matches,away_attack_rating_last_4_matches,home_attack_rating_last_2_home_matches,away_attack_rating_last_2_away_matches
0,Reims,Paris Saint Germain,August 08 2014,Ligue 1,2014/2015,2,2,1.37,2.66,2014-08-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
conditions = [
    clean_df["home_score"] > clean_df["away_score"],
    clean_df["home_score"] < clean_df["away_score"]
]

choices = [
    "Home Win",
    "Away Win"
]

clean_df["match_result"] = np.select(
    conditions,
    choices,
    default="Draw"
)

Why `np.select()`?

This feature could also be created using a `for` loop, which was my first approach.

However, I decided to use `np.select()` because it applies the conditions to the entire DataFrame at once (vectorized operations), making the code more efficient and more consistent with pandas best practices.

The variables `conditions` and `choices` are not reserved keywords. They are simply descriptive variable names chosen to improve readability. They could be renamed if needed.

The only reserved parameter in this function call is `default`, which defines the value assigned when none of the specified conditions are met.

In [85]:
clean_df["match_result"].value_counts()

match_result
Home Win    7270
Away Win    4975
Draw        4087
Name: count, dtype: int64

In [86]:
clean_df[["home_score", "away_score", "match_result"]].head(10)

   home_score  away_score match_result
0           2           2         Draw
1           0           3     Away Win
2           0           2     Away Win
3           0           0         Draw
4           0           1     Away Win
5           1           0     Home Win
6           3           2     Home Win
7           3           3         Draw
8           2           0     Home Win
9           1           2     Away Win

Findings

The `match_result` feature was successfully created.

The distribution of results shows that Home Wins are the most frequent outcome, followed by Away Wins and Draws. This distribution is consistent with the well-known home advantage observed in professional football.

### 3.2. Goal Difference

In [87]:
clean_df["goal_difference"] = clean_df["home_score"] - clean_df["away_score"]

In [88]:
clean_df[["home_score", "away_score", "goal_difference"]].head(5)

   home_score  away_score  goal_difference
0           2           2                0
1           0           3               -3
2           0           2               -2
3           0           0                0
4           0           1               -1

Findings

The `goal_difference` feature was successfully created and validated.

Positive values represent home victories, negative values represent away victories, and zero represents draws.

The observed range (-9 to 9) appears realistic for professional football matches, indicating that the feature has been calculated correctly.

Now created `goal_difference` let test some statistics

In [89]:
clean_df["goal_difference"].describe()

count    16332.000000
mean         0.324516
std          1.831458
min         -9.000000
25%         -1.000000
50%          0.000000
75%          1.000000
max          9.000000
Name: goal_difference, dtype: float64

Some conclusions:

MIN 
Show that largest AWAY victory was by **-9** goals of difference (cause it is negative number)

MAX 
Show that largest HOME victory was by **9** goals of difference (cause it is positive number)

MEDIAN
Value is **0**, meaning that the center of the distribution is a goal difference of zero.
This suggests that most matches are relatively balanced, with many ending in draws or being decided by a small goal margin.

### 3.4.

### 3.5.

### 3.6.

### 3.7.

### 3.8.

### 3.9. Average Team Rating and Rating Difference

As we need TEAM players ratings and not individual ratings, for comparing between teams, we are calculating each TEAM (home and away) ratings and calculating the difference between them, in that case the positive rating will show a better rating for Home team and negative rating will show better rating for away team

`average_team_rating`

Our research question focuses on **team player ratings**, not individual player ratings.

To compare both teams fairly, we calculate the average rating of the home team and the away team using their defense, midfield, and attack ratings.

Finally, we create a new feature called `rating_difference`.

- A **positive** value indicates that the home team has a higher average rating.
- A **negative** value indicates that the away team has a higher average rating.
- A value close to **zero** indicates that both teams have similar overall ratings.

In [93]:
list(clean_df.columns[clean_df.columns.str.contains("ratin")])

['home_defense_rating',
 'away_defense_rating',
 'home_midfield_rating',
 'away_midfield_rating',
 'home_attack_rating',
 'away_attack_rating',
 'home_defense_rating_last_4_matches',
 'away_defense_rating_last_4_matches',
 'home_defense_rating_last_2_home_matches',
 'away_defense_rating_last_2_away_matches',
 'home_midfield_rating_last_4_matches',
 'away_midfield_rating_last_4_matches',
 'home_midfield_rating_last_2_home_matches',
 'away_midfield_rating_last_2_away_matches',
 'home_attack_rating_last_4_matches',
 'away_attack_rating_last_4_matches',
 'home_attack_rating_last_2_home_matches',
 'away_attack_rating_last_2_away_matches']

In [97]:
clean_df["average_home_team_rating"] = clean_df[["home_attack_rating", "home_midfield_rating", "home_defense_rating"]].mean(axis=1) #axis 0 columns, 1 rows

In [98]:
clean_df["average_away_team_rating"] = clean_df[["away_attack_rating", "away_midfield_rating", "away_defense_rating"]].mean(axis=1) #axis 0 columns, 1 rows

In [99]:
clean_df["rating_difference"] = clean_df["average_home_team_rating"] - clean_df["average_away_team_rating"]

In [100]:
clean_df[["average_home_team_rating", "average_away_team_rating", "rating_difference"]].head(5)

   average_home_team_rating  average_away_team_rating  rating_difference
0                  6.862000                  7.026667          -0.164667
1                  6.278056                  7.997333          -1.719278
2                  6.246833                  7.390222          -1.143389
3                  6.810889                  6.705333           0.105556
4                  6.654667                  7.151333          -0.496667

In [101]:
clean_df[["average_home_team_rating","average_away_team_rating","rating_difference"]].describe()

       average_home_team_rating  average_away_team_rating  rating_difference
count              16332.000000              16332.000000       16332.000000
mean                   6.950670                  6.800973           0.149697
std                    0.459847                  0.446564           0.847919
min                    5.371111                  5.366000          -3.450000
25%                    6.629292                  6.488264          -0.411736
50%                    6.916750                  6.770333           0.139694
75%                    7.242056                  7.081583           0.715208
max                    8.880000                  9.103333           3.415611

Findings

The average team ratings were successfully calculated using the defense, midfield, and attack ratings.

The new `rating_difference` feature compares the overall quality of both teams before each match.

Positive values indicate a stronger home team, negative values indicate a stronger away team, while values close to zero suggest both teams have similar overall ratings.

This feature will support Research Question 4 by allowing us to investigate whether stronger team ratings are associated with better match performance.